save_folder: Experiments/test

Training_Dataset:
  patient_data_list_path: "dataset/lists/sample_100.txt"
  no_classes: 4

Validation_Dataset:
  patient_data_list_path: "dataset/lists/sample_100.txt"
  no_classes: 4

Test_Dataset:
  patient_data_list_path: "dataset/lists/sample_100.txt"
  no_classes: 4

Model:
  in_channels: 3
  out_channels: 4
  img_size: [144, 240, 240]
  feature_size: 16
  hidden_size: 768
  mlp_dim: 3072
  num_heads: 12
  pos_embed: "perceptron"
  norm_name: "instance"
  conv_block: True
  res_block: True
  dropout_rate: 0

Trainer:
  number_of_epochs: 10
  loss:
    path: monai.losses.DiceCELoss
    params:
      include_background: True
      to_onehot_y: False
      sigmoid: False
      softmax: False
      other_act: None
      squared_pred: False
      jaccard: False
      reduction: 'mean'
      smooth_nr: 1e-05
      smooth_dr: 1e-05
      batch: False
      ce_weight: None
      lambda_dice: 1.0
      lambda_ce: 1.0
  optimizer:
    path: torch.optim.Adam
    params:
        lr: 0.0001


